default:
  image: gitlab.ensimag.fr:5050/reigniep/dockergl

deploy-prod:
  stage: deploy
  rules:     
      - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH
  before_script:
    - git checkout $CI_DEFAULT_BRANCH
    - git config --global --add safe.directory /builds/gl2024/gr9/gl42
  script:
    - export PATH=$HOME/ensimag/GL/global/bin:$PATH
    - export PATH=$JAVA_HOME/bin:"$PATH"
    - export PATH=$HOME/ensimag/GL/Projet_GL/src/main/bin:"$PATH"
    - export PATH=$HOME/ensimag/GL/Projet_GL/src/test/script:"$PATH"
    - export PATH=$HOME/ensimag/GL/Projet_GL/src/test/script/launchers:"$PATH"%
    - mvn compile
    - ./src/test/script/tests.py -f
