default:
  image: gitlab.ensimag.fr:5050/reigniep/dockergl

deploy-prod:
  stage: deploy
  rules:     
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH
  before_script:
    - git config --global --add safe.directory /builds/gl2024/gr9/gl42
    - git fetch origin $CI_COMMIT_BRANCH
    - git checkout $CI_COMMIT_BRANCH
  script:
    - JAVA_HOME=/usr/lib/jvm/java-1.18.0-openjdk-amd64 
    - M2_HOME=/opt/maven
    - MAVEN_HOME=$M2_HOME
    - PATH=$M2_HOME/bin:"$PATH" 
    - PATH=/matieres/4MMPGL/GL/global/bin:"$PATH" 
    - PATH=$JAVA_HOME/bin:"$PATH" 
    - PATH=/home/gl/Projet_GL/src/main/bin:"$PATH" 
    - PATH=/home/gl/Projet_GL/src/test/script:"$PATH" 
    - PATH=/home/gl/Projet_GL/src/test/script/launchers:"$PATH" 
    - export PATH
    - mvn test-compile
    - mvn test
    - mvn clean
